In [1]:
import sklearn

In [2]:
import pandas as pd

In [7]:
!dir .\files\advertising.csv

 D 드라이브의 볼륨: DATA
 볼륨 일련 번호: 08D4-18A8

 d:\Develops\test_machinelearning\files 디렉터리

2021-07-01 (목)  오후 02:29           107,937 advertising.csv
               1개 파일             107,937 바이트
               0개 디렉터리  263,559,839,744 바이트 남음


In [8]:
pd_data = pd.read_csv('./files/advertising.csv')

In [9]:
pd_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64  
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   object 
 5   City                      1000 non-null   object 
 6   Male                      1000 non-null   int64  
 7   Country                   1000 non-null   object 
 8   Timestamp                 1000 non-null   object 
 9   Clicked on Ad             1000 non-null   int64  
dtypes: float64(3), int64(3), object(4)
memory usage: 78.2+ KB


In [10]:
pd_data.shape

(1000, 10)

In [11]:
pd_data

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                       68.95   35     61833.90                256.09   
1                       80.23   31     68441.85                193.77   
2                       69.47   26     59785.94                236.50   
3                       74.15   29     54806.18                245.89   
4                       68.37   35     73889.99                225.58   
..                        ...  ...          ...                   ...   
995                     72.97   30     71384.57                208.58   
996                     51.30   45     67782.17                134.42   
997                     51.63   51     42415.72                120.37   
998                     55.55   19     41920.79                187.95   
999                     45.01   26     29875.80                178.35   

                             Ad Topic Line            City  Male  \
0       Cloned 5thgeneration orchestration     Wrightburgh     0   
1       Monitored national standardization       West Jodi     1   
2         Organic bottom-line service-desk        Davidton     0   
3    Triple-buffered reciprocal time-frame  West Terrifurt     1   
4            Robust logistical utilization    South Manuel     0   
..                                     ...             ...   ...   
995          Fundamental modular algorithm       Duffystad     1   
996        Grass-roots cohesive monitoring     New Darlene     1   
997           Expanded intangible solution   South Jessica     1   
998   Proactive bandwidth-monitored policy     West Steven     0   
999        Virtual 5thgeneration emulation     Ronniemouth     0   

                    Country            Timestamp  Clicked on Ad  
0                   Tunisia   2016-03-27 0:53:11              0  
1                     Nauru   2016-04-04 1:39:02              0  
2                San Marino  2016-03-13 20:35:42              0  
3                     Italy   2016-01-10 2:31:19              0  
4                   Iceland   2016-06-03 3:36:18              0  
..                      ...                  ...            ...  
995                 Lebanon  2016-02-11 21:49:00              1  
996  Bosnia and Herzegovina   2016-04-22 2:07:01              1  
997                Mongolia  2016-02-01 17:24:57              1  
998               Guatemala   2016-03-24 2:35:54              0  
999                  Brazil  2016-06-03 21:43:21              1  

[1000 rows x 10 columns]

In [12]:
x = pd_data[['Daily Time Spent on Site', 'Age', 'Area Income', 'Daily Internet Usage', 'Male']]
y = pd_data[['Clicked on Ad']]

In [13]:
x.shape, y.shape, type(x), type(y)

((1000, 5),
 (1000, 1),
 pandas.core.frame.DataFrame,
 pandas.core.frame.DataFrame)

In [14]:
import numpy as np

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((750, 5), (250, 5), (750, 1), (250, 1))

In [17]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [18]:
log.fit(x_train, y_train)

d:\python36\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [19]:
log.coef_, log.intercept_

(array([[-7.04350082e-02,  2.70648255e-01, -1.37542799e-05,
         -2.22305983e-02,  2.04487355e-03]]),
 array([0.00549936]))

In [20]:
log.predict_proba(x_train[500:504])

array([[0.94413452, 0.05586548],
       [0.34690752, 0.65309248],
       [0.98191615, 0.01808385],
       [0.07994809, 0.92005191]])

In [21]:
log.predict(x_train[500:504])

array([0, 1, 0, 1], dtype=int64)

In [22]:
0.94413452+0.05586548

1.0

In [23]:
from sklearn import metrics

In [25]:
y_pred = log.predict(x_train)
y_pred.shape, y_train.shape

((750,), (750, 1))

In [26]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,

In [27]:
y_train

Clicked on Ad
24               1
933              1
149              1
942              1
953              1
..             ...
361              1
15               1
847              0
222              1
510              1

[750 rows x 1 columns]

In [28]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.94      0.90       370
           1       0.93      0.87      0.90       380

    accuracy                           0.90       750
   macro avg       0.90      0.90      0.90       750
weighted avg       0.90      0.90      0.90       750



In [29]:
metrics.confusion_matrix(y_train, y_pred)

array([[346,  24],
       [ 50, 330]], dtype=int64)

In [30]:
import pickle

In [32]:
pickle.dump(log, open('./saves/advertising.pkl','wb'))