In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
type(iris)

sklearn.utils.Bunch

In [4]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
x = iris.data
y = iris.target
x.shape, y.shape, type(x), type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

In [7]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [14]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [15]:
log.fit(x_train, y_train)

d:\python36\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [16]:
log.coef_, log.intercept_

(array([[-0.45039385,  0.90057448, -2.31802434, -0.97313023],
        [ 0.34901793, -0.3832209 , -0.194378  , -0.78449093],
        [ 0.10137592, -0.51735358,  2.51240234,  1.75762116]]),
 array([  9.47462442,   3.06582469, -12.54044911]))

y = -0.45039385x_1 + 0.90057448x_2 + -2.31802434x_3 + -0.97313023

In [17]:
log.predict_proba(x_train[100:104])

array([[4.95694448e-04, 2.96740147e-01, 7.02764158e-01],
       [2.81421455e-06, 2.85542460e-02, 9.71442940e-01],
       [1.59542795e-02, 7.73344928e-01, 2.10700793e-01],
       [1.32771319e-04, 9.49715503e-02, 9.04895678e-01]])

In [18]:
log.predict(x_train[100:104])

array([2, 2, 1, 2])

가장 큰 값(높은 확률) 위치

In [19]:
4.95694448e-04+2.96740147e-01+7.02764158e-01
2.81421455e-06+2.85542460e-02+9.71442940e-01
1.59542795e-02+7.73344928e-01+2.10700793e-01
1.32771319e-04+9.49715503e-02+9.04895678e-01

0.999999999619

evaluation

In [21]:
from sklearn import metrics

In [23]:
y_pred = log.predict(x_train)
y_pred.shape, y_train.shape

((112,), (112,))

In [24]:
y_pred

array([2, 0, 0, 0, 1, 2, 0, 0, 0, 1, 1, 0, 2, 1, 2, 2, 0, 1, 0, 1, 0, 1,
       0, 2, 2, 2, 1, 2, 2, 2, 2, 1, 0, 2, 1, 1, 1, 0, 2, 0, 2, 1, 2, 0,
       0, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 1, 1, 1, 0, 2, 2, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 1, 1, 1, 2, 0, 1, 2, 2, 2, 2, 2,
       2, 2, 1, 2, 0, 0, 1, 2, 2, 1, 0, 2, 2, 2, 1, 2, 0, 1, 0, 2, 1, 1,
       1, 1])

In [25]:
y_train

array([2, 0, 0, 0, 1, 2, 0, 0, 0, 1, 1, 0, 2, 1, 2, 2, 0, 1, 0, 1, 0, 1,
       0, 2, 2, 2, 1, 2, 2, 1, 2, 1, 0, 1, 1, 1, 1, 0, 2, 0, 2, 1, 2, 0,
       0, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 1, 1, 1, 0, 2, 2, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 1, 1, 2, 2, 0, 1, 2, 2, 2, 2, 2,
       2, 2, 1, 2, 0, 0, 1, 2, 2, 1, 0, 2, 2, 2, 1, 2, 0, 1, 0, 2, 1, 1,
       1, 1])

In [26]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.97      0.95      0.96        38
           2       0.95      0.97      0.96        37

    accuracy                           0.97       112
   macro avg       0.97      0.97      0.97       112
weighted avg       0.97      0.97      0.97       112



In [28]:
metrics.confusion_matrix(y_train, y_pred)

array([[37,  0,  0],
       [ 0, 36,  2],
       [ 0,  1, 36]], dtype=int64)